#!/usr/bin/env bash

username="$1"
repoName="$2"

githubRes=$(curl -s -u "$username" https://api.github.com/user/repos -d "{\"name\":\"$repoName\",\"auto_init\":true}")

githubName=$(echo $githubRes | jq ".name")
repoUrl=$(echo $githubRes | jq -r ".ssh_url")
echo $repoUrl

if [ $githubName != null ]
then
  git clone ${repoUrl}

else
  echo $(echo $githubRes | jq ".message")
fi